/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HamChinh;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author MyPC
 */
public class GiaoDien extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDien
     */
   
    private BufferedImage IChuot;
    public GiaoDien() {
        initComponents();
        setIcon();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTGRDoHoa = new javax.swing.ButtonGroup();
        JPMain = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("bgmain.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        JPMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JPShape = new javax.swing.JPanel()
        {
            ImageIcon icon = new ImageIcon("bg.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        }
        ;
        btLine = new javax.swing.JButton();
        btCircle = new javax.swing.JButton();
        btSquare = new javax.swing.JButton();
        btRectangle = new javax.swing.JButton();
        btEclip = new javax.swing.JButton();
        btRhombus = new javax.swing.JButton();
        JPTool = new javax.swing.JPanel();
        btDelete = new javax.swing.JButton();
        JPOther = new javax.swing.JPanel();
        R2D = new javax.swing.JRadioButton();
        R3D = new javax.swing.JRadioButton();
        JPDraw = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kỹ Thuật Đồ Họa");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JPMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPMain.setPreferredSize(new java.awt.Dimension(1022, 694));

        JPMenu.setBackground(new java.awt.Color(153, 153, 153));
        JPMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        JPMenu.setPreferredSize(new java.awt.Dimension(300, 690));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LỰA CHỌN VẼ");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/paint-palette.png"))); // NOI18N
        jLabel2.setText("Lựa Chọn Hình");
        jLabel2.setIconTextGap(10);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/tools.png"))); // NOI18N
        jLabel3.setText("Công Cụ");
        jLabel3.setIconTextGap(10);

        JPShape.setBackground(new java.awt.Color(255, 255, 255));
        JPShape.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        JPShape.setPreferredSize(new java.awt.Dimension(300, 223));

        btLine.setForeground(Color.GRAY);
        btLine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/diagonal-line.png"))); // NOI18N
        btLine.setText("Đường Thẳng");
        btLine.setBorder(null);
        btLine.setBorderPainted(false);
        btLine.setContentAreaFilled(false);
        btLine.setIconTextGap(6);
        btLine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLineMouseClicked(evt);
            }
        });
        btLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLineActionPerformed(evt);
            }
        });

        btCircle.setForeground(Color.GRAY);
        btCircle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/circle.png"))); // NOI18N
        btCircle.setText("Hình Tròn");
        btCircle.setBorder(null);
        btCircle.setBorderPainted(false);
        btCircle.setContentAreaFilled(false);
        btCircle.setIconTextGap(6);
        btCircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCircleActionPerformed(evt);
            }
        });

        btSquare.setForeground(Color.GRAY);
        btSquare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/square.png"))); // NOI18N
        btSquare.setText("Hình Vuông");
        btSquare.setBorder(null);
        btSquare.setBorderPainted(false);
        btSquare.setContentAreaFilled(false);
        btSquare.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSquare.setIconTextGap(6);
        btSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSquareActionPerformed(evt);
            }
        });

        btRectangle.setForeground(Color.GRAY);
        btRectangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/rectangular-geometrical-shape-outline.png"))); // NOI18N
        btRectangle.setText("Hình Chữ Nhật");
        btRectangle.setBorder(null);
        btRectangle.setBorderPainted(false);
        btRectangle.setContentAreaFilled(false);
        btRectangle.setIconTextGap(6);
        btRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRectangleActionPerformed(evt);
            }
        });

        btEclip.setForeground(Color.GRAY);
        btEclip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/ellipse-outline-shape-variant.png"))); // NOI18N
        btEclip.setText("Hình Eclip");
        btEclip.setBorder(null);
        btEclip.setBorderPainted(false);
        btEclip.setContentAreaFilled(false);
        btEclip.setIconTextGap(6);
        btEclip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEclipActionPerformed(evt);
            }
        });

        btRhombus.setForeground(Color.GRAY);
        btRhombus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/rhombus.png"))); // NOI18N
        btRhombus.setText("Hình Tứ Giác");
        btRhombus.setBorder(null);
        btRhombus.setBorderPainted(false);
        btRhombus.setContentAreaFilled(false);
        btRhombus.setIconTextGap(6);
        btRhombus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRhombusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPShapeLayout = new javax.swing.GroupLayout(JPShape);
        JPShape.setLayout(JPShapeLayout);
        JPShapeLayout.setHorizontalGroup(
            JPShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPShapeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btEclip)
                    .addComponent(btLine)
                    .addComponent(btRectangle))
                .addGap(31, 31, 31)
                .addGroup(JPShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSquare)
                    .addComponent(btCircle)
                    .addComponent(btRhombus))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        JPShapeLayout.setVerticalGroup(
            JPShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPShapeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLine)
                    .addComponent(btCircle))
                .addGap(18, 18, 18)
                .addGroup(JPShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRectangle)
                    .addComponent(btSquare))
                .addGap(29, 29, 29)
                .addGroup(JPShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRhombus)
                    .addComponent(btEclip))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        JPTool.setBackground(new java.awt.Color(255, 255, 255));
        JPTool.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        JPTool.setPreferredSize(new java.awt.Dimension(300, 304));

        btDelete.setBackground(new java.awt.Color(255, 255, 255));
        btDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btDelete.setForeground(Color.GRAY);
        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/CLose.png"))); // NOI18N
        btDelete.setMnemonic('X');
        btDelete.setText("Xóa");
        btDelete.setBorder(null);
        btDelete.setBorderPainted(false);
        btDelete.setContentAreaFilled(false);
        btDelete.setIconTextGap(6);

        javax.swing.GroupLayout JPToolLayout = new javax.swing.GroupLayout(JPTool);
        JPTool.setLayout(JPToolLayout);
        JPToolLayout.setHorizontalGroup(
            JPToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPToolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPToolLayout.setVerticalGroup(
            JPToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPToolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btDelete)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        JPOther.setBackground(new java.awt.Color(255, 255, 255));
        JPOther.setPreferredSize(new java.awt.Dimension(300, 55));

        BTGRDoHoa.add(R2D);
        R2D.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        R2D.setForeground(new java.awt.Color(102, 102, 102));
        R2D.setMnemonic('2');
        R2D.setText("2D");
        R2D.setToolTipText("ALT+2");
        R2D.setContentAreaFilled(false);
        R2D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/square-shadow.png"))); // NOI18N
        R2D.setIconTextGap(6);
        R2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2DActionPerformed(evt);
            }
        });

        BTGRDoHoa.add(R3D);
        R3D.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        R3D.setForeground(new java.awt.Color(102, 102, 102));
        R3D.setMnemonic('3');
        R3D.setText("3D");
        R3D.setToolTipText("ALT+3");
        R3D.setContentAreaFilled(false);
        R3D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/cubes.png"))); // NOI18N
        R3D.setIconTextGap(6);
        R3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3DActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPOtherLayout = new javax.swing.GroupLayout(JPOther);
        JPOther.setLayout(JPOtherLayout);
        JPOtherLayout.setHorizontalGroup(
            JPOtherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOtherLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(R2D)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(R3D)
                .addGap(47, 47, 47))
        );
        JPOtherLayout.setVerticalGroup(
            JPOtherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOtherLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPOtherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R2D)
                    .addComponent(R3D))
                .addContainerGap())
        );

        javax.swing.GroupLayout JPMenuLayout = new javax.swing.GroupLayout(JPMenu);
        JPMenu.setLayout(JPMenuLayout);
        JPMenuLayout.setHorizontalGroup(
            JPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPOther, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addComponent(JPShape, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
            .addComponent(JPTool, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
            .addGroup(JPMenuLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        JPMenuLayout.setVerticalGroup(
            JPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPMenuLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPOther, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPTool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPDraw.setBackground(new java.awt.Color(255, 255, 255));
        JPDraw.setPreferredSize(new java.awt.Dimension(708, 27));

        javax.swing.GroupLayout JPDrawLayout = new javax.swing.GroupLayout(JPDraw);
        JPDraw.setLayout(JPDrawLayout);
        JPDrawLayout.setHorizontalGroup(
            JPDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        JPDrawLayout.setVerticalGroup(
            JPDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JPMainLayout = new javax.swing.GroupLayout(JPMain);
        JPMain.setLayout(JPMainLayout);
        JPMainLayout.setHorizontalGroup(
            JPMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPMainLayout.createSequentialGroup()
                .addComponent(JPMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPMainLayout.setVerticalGroup(
            JPMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPDraw, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
            .addComponent(JPMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void HTD2D()
    {
        Graphics g=JPDraw.getGraphics();
        g.setColor(Color.RED);
        g.drawString("X", 360, 10);
        g.drawString("Y", 690, 370);
        g.setColor(Color.BLUE);
        g.drawLine(350, 0, 350, 700);
        g.drawLine(0, 350, 700, 350);
      
       
        
    }
    public void HTD3D()
    {
        Graphics g=JPDraw.getGraphics();
        g.setColor(Color.RED);
        g.drawString("X", 360, 10);
        g.drawString("Y", 690, 370);
        g.setColor(Color.BLUE);
        g.drawLine(354, 0, 354, 708);
        g.drawLine(0, 354, 708, 354);
    }

    private void R3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3DActionPerformed
        // TODO add your handling code here:
        R3D.setForeground(Color.red);
        R2D.setForeground(Color.gray);
    }//GEN-LAST:event_R3DActionPerformed

    private void R2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2DActionPerformed
        // TODO add your handling code here:
        R2D.setForeground(Color.red);
        R3D.setForeground(Color.gray);
        HTD2D();
        
    }//GEN-LAST:event_R2DActionPerformed

    private void btRhombusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRhombusActionPerformed
        // TODO add your handling code here:
        if(R2D.isSelected())
        {
            btRhombus.setFont(new java.awt.Font("Tahoma", 1, 11));
            btLine.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btRectangle.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btCircle.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btSquare.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btEclip.setFont(new Font("Tahoma", Font.PLAIN, 11));
        }
    }//GEN-LAST:event_btRhombusActionPerformed

    private void btEclipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEclipActionPerformed
        // TODO add your handling code here:
        if(R2D.isSelected())
        {
            btEclip.setFont(new java.awt.Font("Tahoma", 1, 11));
            btCircle.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btRectangle.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btSquare.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btRhombus.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btLine.setFont(new Font("Tahoma", Font.PLAIN, 11));
        }
    }//GEN-LAST:event_btEclipActionPerformed

    private void btRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRectangleActionPerformed
        // TODO add your handling code here:
        if(R2D.isSelected())
        {
            btRectangle.setFont(new java.awt.Font("Tahoma", 1, 11));
            btCircle.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btLine.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btSquare.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btRhombus.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btEclip.setFont(new Font("Tahoma", Font.PLAIN, 11));
        }
    }//GEN-LAST:event_btRectangleActionPerformed

    private void btSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSquareActionPerformed
        // TODO add your handling code here:
        if(R2D.isSelected())
        {
            btSquare.setFont(new java.awt.Font("Tahoma", 1, 11));
            btLine.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btRectangle.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btCircle.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btRhombus.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btEclip.setFont(new Font("Tahoma", Font.PLAIN, 11));
        }

    }//GEN-LAST:event_btSquareActionPerformed

    private void btCircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCircleActionPerformed
        // TODO add your handling code here:
        if(R2D.isSelected())
        {
            btCircle.setFont(new java.awt.Font("Tahoma", 1, 11));
            btLine.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btRectangle.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btSquare.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btRhombus.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btEclip.setFont(new Font("Tahoma", Font.PLAIN, 11));
        }
    }//GEN-LAST:event_btCircleActionPerformed

    private void btLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLineActionPerformed
        // TODO add your handling code here:
        if(R2D.isSelected())
        {
            btLine.setFont(new java.awt.Font("Tahoma", 1, 11));
            btCircle.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btRectangle.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btSquare.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btRhombus.setFont(new Font("Tahoma", Font.PLAIN, 11));
            btEclip.setFont(new Font("Tahoma", Font.PLAIN, 11));
             
        }
    }//GEN-LAST:event_btLineActionPerformed

    private void btLineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLineMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btLineMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BTGRDoHoa;
    private javax.swing.JPanel JPDraw;
    private javax.swing.JPanel JPMain;
    private javax.swing.JPanel JPMenu;
    private javax.swing.JPanel JPOther;
    private javax.swing.JPanel JPShape;
    private javax.swing.JPanel JPTool;
    private javax.swing.JRadioButton R2D;
    private javax.swing.JRadioButton R3D;
    private javax.swing.JButton btCircle;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEclip;
    private javax.swing.JButton btLine;
    private javax.swing.JButton btRectangle;
    private javax.swing.JButton btRhombus;
    private javax.swing.JButton btSquare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
         Image image = Toolkit.getDefaultToolkit().getImage("cursor.png");
        Point hotspot = new Point(0,0);
        Cursor cursor = Toolkit.getDefaultToolkit().createCustomCursor(image, hotspot, "pencil");
        setCursor(cursor);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/HinhAnh/paint-brush.png")));
    }
}
